-- migrate:up

-- ============================================================
-- CHUNK RELATIONS ENHANCEMENTS (M3c-1, ADR-050)
-- Add contextual labels and provenance tracking to pre-computed
-- passage relations. Labels are generated by Claude at index-time
-- to honor the spirit of the teachings (PRI-03).
-- ============================================================
ALTER TABLE chunk_relations
  ADD COLUMN IF NOT EXISTS relation_label TEXT,
  ADD COLUMN IF NOT EXISTS tagged_by TEXT NOT NULL DEFAULT 'auto'
    CHECK (tagged_by IN ('auto', 'ai_suggested', 'human_confirmed')),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Index for efficient lookup of relations needing human review
CREATE INDEX IF NOT EXISTS idx_chunk_relations_pending
  ON chunk_relations(tagged_by) WHERE tagged_by = 'ai_suggested';

-- ============================================================
-- EXTERNAL REFERENCES — Reverse Bibliography (M3c-8, DES-027)
-- Canonical external sources that Yogananda engages with:
-- Bhagavad Gita, Bible, Yoga Sutras, Rubaiyat, etc.
-- ============================================================
CREATE TABLE IF NOT EXISTS external_references (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  author TEXT,
  tradition TEXT,
  description TEXT,
  url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER external_references_updated_at
  BEFORE UPDATE ON external_references
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- CHUNK ↔ EXTERNAL REFERENCE JUNCTION (M3c-8)
-- Links passages to the external sources they reference.
-- Three-state provenance: auto (embedding-based), ai_suggested
-- (Claude-classified), human_confirmed (editor-verified).
-- ============================================================
CREATE TABLE IF NOT EXISTS chunk_external_references (
  chunk_id UUID NOT NULL REFERENCES book_chunks(id) ON DELETE CASCADE,
  reference_id UUID NOT NULL REFERENCES external_references(id) ON DELETE CASCADE,
  context TEXT,
  tagged_by TEXT NOT NULL DEFAULT 'auto'
    CHECK (tagged_by IN ('auto', 'ai_suggested', 'human_confirmed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (chunk_id, reference_id)
);

CREATE INDEX IF NOT EXISTS idx_chunk_ext_refs_reference
  ON chunk_external_references(reference_id);

-- ============================================================
-- EDITORIAL THREADS (M3c-7, DES-026)
-- Curated multi-book reading paths: human-selected passages
-- sequenced to trace a spiritual theme as a coherent progression.
-- ============================================================
CREATE TABLE IF NOT EXISTS editorial_threads (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  theme_id UUID REFERENCES teaching_topics(id),
  is_published BOOLEAN NOT NULL DEFAULT false,
  created_by TEXT NOT NULL DEFAULT 'editorial',
  -- Calendar journey extensions (M3c-11, DES-045)
  journey_type TEXT CHECK (journey_type IN ('evergreen', 'seasonal', 'annual')),
  journey_duration_days INTEGER,
  journey_start_month INTEGER,
  journey_start_day INTEGER,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER editorial_threads_updated_at
  BEFORE UPDATE ON editorial_threads
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- THREAD PASSAGES (M3c-7)
-- Individual passages within a reading thread, with optional
-- editorial transition notes between them.
-- ============================================================
CREATE TABLE IF NOT EXISTS thread_passages (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  thread_id UUID NOT NULL REFERENCES editorial_threads(id) ON DELETE CASCADE,
  chunk_id UUID NOT NULL REFERENCES book_chunks(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  transition_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (thread_id, position)
);

CREATE INDEX IF NOT EXISTS idx_thread_passages_thread
  ON thread_passages(thread_id, position);

-- ============================================================
-- PEOPLE — Spiritual Figures (M3c-12, ADR-036/037)
-- Gurus, monastics, historical figures referenced in the corpus.
-- ============================================================
CREATE TABLE IF NOT EXISTS people (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  honorific TEXT,
  person_type TEXT NOT NULL DEFAULT 'spiritual_figure'
    CHECK (person_type IN ('guru_lineage', 'monastic', 'spiritual_figure', 'historical')),
  era TEXT,
  description TEXT,
  image_url TEXT,
  is_living BOOLEAN DEFAULT false,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER people_updated_at
  BEFORE UPDATE ON people
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- PERSON RELATIONS (M3c-12)
-- Relationships between spiritual figures: teacher-student,
-- presidential succession, editorial collaboration.
-- ============================================================
CREATE TABLE IF NOT EXISTS person_relations (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  source_person_id UUID NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  target_person_id UUID NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  relation_type TEXT NOT NULL
    CHECK (relation_type IN (
      'teacher_of', 'student_of',
      'succeeded_by', 'preceded_by',
      'mentored_by', 'edited_works_of',
      'collaborated_with'
    )),
  start_year INTEGER,
  end_year INTEGER,
  description TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_person_id, target_person_id, relation_type)
);

-- ============================================================
-- CHUNK ↔ PEOPLE JUNCTION (M3c-12)
-- Links passages to persons mentioned or discussed.
-- ============================================================
CREATE TABLE IF NOT EXISTS chunk_people (
  chunk_id UUID NOT NULL REFERENCES book_chunks(id) ON DELETE CASCADE,
  person_id UUID NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  tagged_by TEXT NOT NULL DEFAULT 'auto'
    CHECK (tagged_by IN ('auto', 'ai_suggested', 'human_confirmed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (chunk_id, person_id)
);

CREATE INDEX IF NOT EXISTS idx_chunk_people_person
  ON chunk_people(person_id);

-- ============================================================
-- SEED DATA: Core External References
-- ============================================================
INSERT INTO external_references (slug, title, author, tradition, description) VALUES
  ('bhagavad-gita', 'Bhagavad Gita', 'Vyasa', 'Hindu', 'The divine song — Krishna''s counsel to Arjuna on the battlefield of Kurukshetra. Central scripture that Yogananda devoted two volumes to interpreting.'),
  ('bible', 'The Bible', NULL, 'Christian', 'Hebrew Bible and New Testament. Yogananda frequently drew parallels between Christ''s teachings and those of Krishna.'),
  ('yoga-sutras', 'Yoga Sutras', 'Patanjali', 'Yogic', 'The foundational text of Raja Yoga. Yogananda references Patanjali''s systematic approach to meditation throughout his works.'),
  ('rubaiyat', 'Rubáiyát of Omar Khayyám', 'Omar Khayyám', 'Sufi', 'Persian mystical poetry that Yogananda interpreted as a spiritual allegory in Wine of the Mystic.'),
  ('upanishads', 'The Upanishads', NULL, 'Hindu', 'Ancient Vedantic wisdom texts exploring the nature of Brahman and Atman.'),
  ('mahabharata', 'Mahabharata', 'Vyasa', 'Hindu', 'The great Indian epic containing the Bhagavad Gita and many stories Yogananda references.'),
  ('ramayana', 'Ramayana', 'Valmiki', 'Hindu', 'The epic of Lord Rama, referenced in discussions of dharma and devotion.'),
  ('gospel-of-john', 'Gospel of John', NULL, 'Christian', 'Yogananda particularly drew from John''s mystical account of Christ''s life and teachings.'),
  ('revelation', 'Book of Revelation', NULL, 'Christian', 'Yogananda interpreted the apocalyptic imagery as describing stages of spiritual awakening.')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- SEED DATA: Core Spiritual Figures
-- ============================================================
INSERT INTO people (slug, name, honorific, person_type, era, description, sort_order) VALUES
  ('yogananda', 'Paramahansa Yogananda', 'Paramahansa', 'guru_lineage', '1893–1952', 'Founder of Self-Realization Fellowship, author of Autobiography of a Yogi. Brought Kriya Yoga to the West.', 1),
  ('sri-yukteswar', 'Sri Yukteswar Giri', 'Swami', 'guru_lineage', '1855–1936', 'Yogananda''s guru. Jnanavatar — incarnation of wisdom. Author of The Holy Science.', 2),
  ('lahiri-mahasaya', 'Lahiri Mahasaya', 'Yogavatar', 'guru_lineage', '1828–1895', 'Sri Yukteswar''s guru. Revived Kriya Yoga in modern times. The "householder yogi" of Benares.', 3),
  ('babaji', 'Mahavatar Babaji', 'Mahavatar', 'guru_lineage', NULL, 'The deathless guru of the Kriya lineage. Lahiri Mahasaya''s guru.', 4),
  ('krishna', 'Lord Krishna', 'Bhagavan', 'spiritual_figure', NULL, 'Divine incarnation and speaker of the Bhagavad Gita. Central figure in Yogananda''s scriptural interpretations.', 5),
  ('christ', 'Jesus Christ', NULL, 'spiritual_figure', NULL, 'Yogananda devoted extensive commentary to Christ''s teachings, finding deep unity with the yoga tradition.', 6),
  ('divine-mother', 'Divine Mother', NULL, 'spiritual_figure', NULL, 'The feminine aspect of God. Yogananda''s primary form of devotion and personal relationship with the Infinite.', 7),
  ('daya-mata', 'Sri Daya Mata', 'Sri', 'monastic', '1914–2010', 'Third president of SRF (1955–2010). Direct disciple of Yogananda. Author of Finding the Joy Within You.', 8),
  ('mrinalini-mata', 'Sri Mrinalini Mata', 'Sri', 'monastic', '1931–2017', 'Fourth president of SRF (2010–2017). Direct disciple of Yogananda.', 9),
  ('rajarsi-janakananda', 'Rajarsi Janakananda', 'Rajarsi', 'monastic', '1892–1955', 'Second president of SRF (1952–1955). Yogananda called him his "saint of saints."', 10),
  ('brother-chidananda', 'Brother Chidananda', 'Brother', 'monastic', NULL, 'Current president of SRF. Announced the Online Teachings Portal initiative.', 11),
  ('anandamayi-ma', 'Anandamayi Ma', 'Ma', 'spiritual_figure', '1896–1982', 'Bengali saint described by Yogananda in Autobiography of a Yogi as "joy-permeated mother."', 12)
ON CONFLICT (slug) DO NOTHING;

-- migrate:down

DROP TABLE IF EXISTS chunk_people;
DROP TABLE IF EXISTS person_relations;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS thread_passages;
DROP TABLE IF EXISTS editorial_threads;
DROP TABLE IF EXISTS chunk_external_references;
DROP TABLE IF EXISTS external_references;

ALTER TABLE chunk_relations
  DROP COLUMN IF EXISTS relation_label,
  DROP COLUMN IF EXISTS tagged_by,
  DROP COLUMN IF EXISTS updated_at;
